// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CollapseController from "./collapse_controller.js"
application.register("collapse", CollapseController)

import FilmographyController from "./filmography_controller.js"
application.register("filmography", FilmographyController)

import YoutubePlayerController from "./youtube_player_controller.js"
application.register("youtube-player", YoutubePlayerController)
